"""Seed the database with mock dog profiles and a demo user."""

from app.database import SessionLocal, engine, Base
from app.models import Dog, User, SizeEnum, SexEnum, CoatLengthEnum


MOCK_DOGS = [
    Dog(
        name="Buddy",
        breed="Golden Retriever",
        size=SizeEnum.large,
        age_years=3,
        weight_lbs=70,
        color="Golden",
        description="Friendly and loyal. Loves fetch and belly rubs.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.long,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=1",
    ),
    Dog(
        name="Luna",
        breed="German Shepherd",
        size=SizeEnum.large,
        age_years=2,
        weight_lbs=65,
        color="Black and Tan",
        description="Smart and protective. Great guard dog.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.medium,
        is_rescue=False,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=2",
    ),
    Dog(
        name="Max",
        breed="French Bulldog",
        size=SizeEnum.small,
        age_years=1.5,
        weight_lbs=25,
        color="Brindle",
        description="Playful couch potato. Snores like a freight train.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.short,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=3",
    ),
    Dog(
        name="Bella",
        breed="Labrador Retriever",
        size=SizeEnum.large,
        age_years=4,
        weight_lbs=75,
        color="Chocolate",
        description="Energetic swimmer. Will eat anything.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.short,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=4",
    ),
    Dog(
        name="Charlie",
        breed="Beagle",
        size=SizeEnum.medium,
        age_years=5,
        weight_lbs=30,
        color="Tricolor",
        description="Nose-driven explorer. Howls at squirrels.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.short,
        is_rescue=False,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=5",
    ),
    Dog(
        name="Franklin",
        breed="Goldendoodle",
        size=SizeEnum.medium,
        age_years=2,
        weight_lbs=45,
        color="White",
        description="Hypoallergenic, loves to fetch ball. Ball is life, life is ball!",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.long,
        is_rescue=False,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=6",
    ),
    Dog(
        name="Rocky",
        breed="Rottweiler",
        size=SizeEnum.extra_large,
        age_years=6,
        weight_lbs=110,
        color="Black and Mahogany",
        description="Gentle giant. Thinks he's a lap dog.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.short,
        is_rescue=True,
        good_with_cats=False,
        good_with_kids=False,
        image_url="https://placedog.net/500/500?id=7",
    ),
    Dog(
        name="Sadie",
        breed="Australian Shepherd",
        size=SizeEnum.medium,
        age_years=1,
        weight_lbs=50,
        color="Blue Merle",
        description="Herds everything including the roomba.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.long,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=8",
    ),
    Dog(
        name="Duke",
        breed="Boxer",
        size=SizeEnum.large,
        age_years=3,
        weight_lbs=65,
        color="Fawn",
        description="Bouncy and goofy. Face says grumpy but heart says love.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.short,
        is_rescue=False,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=9",
    ),
    Dog(
        name="Molly",
        breed="Yorkshire Terrier",
        size=SizeEnum.small,
        age_years=7,
        weight_lbs=7,
        color="Blue and Tan",
        description="Tiny but fierce. Rules the house.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.long,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=False,
        image_url="https://placedog.net/500/500?id=10",
    ),
    Dog(
        name="Tucker",
        breed="Siberian Husky",
        size=SizeEnum.large,
        age_years=2,
        weight_lbs=55,
        color="Gray and White",
        description="Talks more than barks. Escape artist.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.long,
        is_rescue=False,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=11",
    ),
    Dog(
        name="Penny",
        breed="Dachshund",
        size=SizeEnum.small,
        age_years=4,
        weight_lbs=11,
        color="Red",
        description="Long and low. Burrows under every blanket.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.short,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=12",
    ),
    Dog(
        name="Bear",
        breed="Bernese Mountain Dog",
        size=SizeEnum.extra_large,
        age_years=3,
        weight_lbs=100,
        color="Tricolor",
        description="Fluffy cloud of love. Drools with affection.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.long,
        is_rescue=False,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=13",
    ),
    Dog(
        name="Coco",
        breed="Shih Tzu",
        size=SizeEnum.small,
        age_years=6,
        weight_lbs=14,
        color="Gold and White",
        description="Professional cuddler. Expert at giving puppy eyes.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.long,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=14",
    ),
    Dog(
        name="Zeus",
        breed="Great Dane",
        size=SizeEnum.extra_large,
        age_years=4,
        weight_lbs=140,
        color="Harlequin",
        description="Gentle giant who's afraid of vacuum cleaners.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.short,
        is_rescue=False,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=15",
    ),
    Dog(
        name="Rosie",
        breed="Pit Bull Terrier",
        size=SizeEnum.medium,
        age_years=2,
        weight_lbs=50,
        color="White with Patches",
        description="Velvet hippo. Wiggles entire body when happy.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.short,
        is_rescue=True,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=16",
    ),
    Dog(
        name="Milo",
        breed="Corgi",
        size=SizeEnum.small,
        age_years=1,
        weight_lbs=28,
        color="Red and White",
        description="Fluffy butt extraordinaire. Herds ankles.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.medium,
        is_rescue=False,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=17",
    ),
    Dog(
        name="Nala",
        breed="Doberman Pinscher",
        size=SizeEnum.large,
        age_years=3,
        weight_lbs=75,
        color="Black and Rust",
        description="Sleek and athletic. Velcro dog who follows you everywhere.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.short,
        is_rescue=True,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=18",
    ),
    Dog(
        name="Finn",
        breed="Border Collie",
        size=SizeEnum.medium,
        age_years=2,
        weight_lbs=40,
        color="Black and White",
        description="Genius-level intelligence. Needs a job or he'll invent one.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.medium,
        is_rescue=False,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=19",
    ),
    Dog(
        name="Willow",
        breed="Cocker Spaniel",
        size=SizeEnum.medium,
        age_years=5,
        weight_lbs=30,
        color="Golden",
        description="Silky ears and soulful eyes. Lives for belly rubs.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.medium,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=20",
    ),
    Dog(
        name="Atlas",
        breed="Pit Bull Terrier",
        size=SizeEnum.medium,
        age_years=3,
        weight_lbs=55,
        color="Gray",
        description="Built like a tank, gentle as a lamb. Champion snuggler.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.short,
        is_rescue=True,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=21",
    ),
    Dog(
        name="Pepper",
        breed="Miniature Schnauzer",
        size=SizeEnum.small,
        age_years=8,
        weight_lbs=15,
        color="Salt and Pepper",
        description="Distinguished gentleman with a magnificent beard.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.wire,
        is_rescue=False,
        good_with_cats=True,
        good_with_kids=False,
        image_url="https://placedog.net/500/500?id=22",
    ),
    Dog(
        name="Hazel",
        breed="Cavalier King Charles Spaniel",
        size=SizeEnum.small,
        age_years=3,
        weight_lbs=16,
        color="Blenheim",
        description="Royal lapdog. Melts into your arms like warm butter.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.medium,
        is_rescue=True,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=23",
    ),
    Dog(
        name="Odin",
        breed="Great Pyrenees",
        size=SizeEnum.extra_large,
        age_years=4,
        weight_lbs=105,
        color="White",
        description="Majestic floof mountain. Guardian of the backyard.",
        sex=SexEnum.male,
        coat_length=CoatLengthEnum.long,
        is_rescue=False,
        good_with_cats=True,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=24",
    ),
    Dog(
        name="Ginger",
        breed="Irish Setter",
        size=SizeEnum.large,
        age_years=2,
        weight_lbs=60,
        color="Red",
        description="Flowing auburn coat and boundless energy. Loves long runs.",
        sex=SexEnum.female,
        coat_length=CoatLengthEnum.long,
        is_rescue=True,
        good_with_cats=False,
        good_with_kids=True,
        image_url="https://placedog.net/500/500?id=25",
    ),
]


def seed_database():
    """Drop all tables, recreate them, and insert mock data."""
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        # Add mock dogs
        db.add_all(MOCK_DOGS)

        # Add a demo user
        demo_user = User(username="demo_user", email="demo@petster.app")
        db.add(demo_user)

        db.commit()
        print(f"✅  Seeded {len(MOCK_DOGS)} dogs and 1 demo user.")
    except Exception as e:
        db.rollback()
        print(f"❌  Seed failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
